name: 'Setup CDash Status'
description: 'Sets up CDash status link for a GitHub commit'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  commit-sha:
    description: 'The commit SHA to set status for'
    required: true
  project:
    description: 'CDash project name'
    required: true
  filter-value:
    description: 'CDash filter value (compare1 parameter)'
    required: false
    default: '61'
  repository:
    description: 'GitHub repository in format owner/repo'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "CI_GITHUB_ROBOT_TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
        echo "COMMIT_SHA=${{ inputs.commit-sha }}" >> $GITHUB_ENV
        echo "CDASH_PROJECT=${{ inputs.project }}" >> $GITHUB_ENV
        echo "CDASH_FILTER_VALUE=${{ inputs.filter-value }}" >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV

    - name: Run CDash status script
      shell: bash
      run: ${{ github.action_path }}/post-cdash-status
