name: 'CDash Status'
description: 'Sets CDash status link for a GitHub commit'
branding:
  icon: box
  color: red
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  project:
    description: 'CDash project name'
    required: true
  repository:
    description: 'GitHub repository in format owner/repo'
    required: false
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ github.event_name == 'pull_request_target' }}
      run: echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> "${GITHUB_ENV}"

    - shell: bash
      if: ${{ github.event_name == 'push' }}
      run: echo "COMMIT_SHA=${{ github.sha }}" >> "${GITHUB_ENV}"

    - name: Set environment variables
      shell: bash
      run: |
        echo "CI_GITHUB_ROBOT_TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
        echo "CDASH_PROJECT=${{ inputs.project }}" >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV

    - name: Run CDash status script
      shell: bash
      run: ${{ github.action_path }}/post-cdash-status
