name: Test Setup CDash Action
on:
  push:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test the action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          project: "TestProject"
          repository: ${{ github.repository }}